### ISSUE TITLE
Invalid device type 13 & KeyError: 70

### ISSUE THREAD

**Issue by colonel-lp** [christopher-strack/spymarine#27]
Just installed this on a Pi Zero 2W, and getting the following when i run your code from the readme:

(i have a pico V1 (running 3.107 latest), 2x SCQ25t(one old style, one new), SC303,  and inclinometer SDI01)

```
mus@ella-zero:~/spymarine $ python3 examples/first.py
ERROR:root:Invalid device type 13
ERROR:root:Invalid device type 13
Traceback (most recent call last):
  File "/home/mus/spymarine/examples/first.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mus/spymarine/examples/first.py", line 8, in main
    await reader.read_sensors()
  File "/usr/local/lib/python3.11/dist-packages/spymarine/device_reader.py", line 62, in read_sensors
    device.update_sensors(property_dict)
  File "/usr/local/lib/python3.11/dist-packages/spymarine/device.py", line 71, in update_sensors
    sensor.update(property_dict)
  File "/usr/local/lib/python3.11/dist-packages/spymarine/sensor.py", line 34, in update
    p = property_dict.values[self.state_index]
        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 70
```

ALSO TRIED TO MAKE A BUG REPORT BUT GET THIS:

```
mus@ella-zero:~/spymarine $ python3 tools/make-debug-report.py
Start creating a debug report in debug.log
Traceback (most recent call last):
  File "/home/mus/spymarine/tools/make-debug-report.py", line 26, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mus/spymarine/tools/make-debug-report.py", line 20, in main
    await reader.read_sensors()
  File "/usr/local/lib/python3.11/dist-packages/spymarine/device_reader.py", line 62, in read_sensors
    device.update_sensors(property_dict)
  File "/usr/local/lib/python3.11/dist-packages/spymarine/device.py", line 71, in update_sensors
    sensor.update(property_dict)
  File "/usr/local/lib/python3.11/dist-packages/spymarine/sensor.py", line 34, in update
    p = property_dict.values[self.state_index]
        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 70
```

IF I MODIFY THE BASIC.PY FILE TO THE FOLLOWING IT WILL CONNECT AND THROW OUT DATA:

```
import asyncio
import spymarine
import logging

logging.basicConfig(level=logging.DEBUG)

async def main():
    async with spymarine.DeviceReader() as reader:
        while True:
            try:
                await reader.read_sensors()
                for device in reader.devices:
                    logging.debug(f"Device: {device}")
                    for sensor in device.sensors:
                        logging.debug(f"Sensor: {sensor}")
                await asyncio.sleep(1)
            except KeyError as e:
                logging.error(f"KeyError: {e}")
            except Exception as e:
                logging.error(f"Unexpected error: {e}")

if __name__ == "__main__":
    asyncio.run(main())
```

Dont shoot me for crap code i'm using AI to help. :)

```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Start UDP broadcast server on port 43210
INFO:root:Discovering IP of Simarine device...
DEBUG:root:Waiting for UDP broadcast message
DEBUG:root:UDP broadcast message received
INFO:root:Found device at 192.168.1.46:5001
DEBUG:root:Connecting to 192.168.1.46:5001...
DEBUG:root:UDP broadcast message received
INFO:root:Fetching device infos
DEBUG:root:Request 'DEVICE_COUNT'
DEBUG:root:UDP broadcast message received
DEBUG:root:UDP broadcast message received
DEBUG:root:Response Message(type=<MessageType.DEVICE_COUNT: b'\x02'>, data=b'\x01\x01\x00\x00\x004\xff\x02\x01\x00\x00\x00E\xff')
DEBUG:root:Request 'DEVICE_INFO'
DEBUG:root:UDP broadcast message received
DEBUG:root:Response Message(type=<MessageType.DEVICE_INFO: b'A'>, data=b'\x00\x01\x00\x00\x00\x00\xff\x01\x03a\xf8\x90\xe7\xff\x00\x00\x00\n\xff\x02\x01\x00\x00\x00\x00\xff\x03\x01\x03+\xe9\xbc\xff\x04\x03^i3\xaf\xff\x00\x00\x00\x01\xff\x05\x03^i3\xaf\xff\x00\x00\x00\x02\xff\x06\x03a\xd2\xf3\xba\xff\x00\x00\x00\x01\xff\x07\x03a\x92\xc7\xac\xff\x00\x00\x00\x02\xff\x08\x03^i3\xaf\xff\x00\x00\x00\x01\x
```

keen to help in any way i can. regards. Col

**Comment by filip373** [comment]
Seems like your issue and setup is very similar to mine described here: https://github.com/christopher-strack/spymarine/issues/20
I even run it on the same Raspberry (Pi Zero 2W).
As suggested by @christopher-strack, this might be related to reading values from the inclinometer.
Maybe your debug data will also help with introducing the support for inclinometer.

**Comment by christopher-strack** [comment]
Hi @colonel-lp, thanks for reporting the issues! As @filip373 points out you have a bunch more Simarine devices that I haven't tested and seem to cause trouble. I appreciate any help from you.

I just released a new version of the library that I would like you to try. The new version should no longer crash but not all devices will have the right sensor values. Could you please try again calling `tools/make-debug-report.py` with v0.6.3 and send a `debug.log`?

**Comment by colonel-lp** [comment]
Thanks for quick update, here is the log:

[debug.log](https://github.com/user-attachments/files/18267901/debug.log)

also don't know if this helps, some values seem incorrect:

[sensors.log](https://github.com/user-attachments/files/18267941/sensors.log)

**Comment by christopher-strack** [comment]
@colonel-lp thanks for providing the information. It looks like the values are quite mixed up, right? I'm not sure the whole approach for mapping the sensor values that I adopted is working for your case. I'm a bit unsure whether I'm able to solve this problem remotely (and in reasonable time).

If you are still up for trying, I would appreciate the current sensor values for the batteries and temperatures so I have a reference point (either written out or by simple creating screenshots for the Simarine app). Ideally you provide a `debug.log` from roughly the same moment (no need to be perfect here).

**Comment by colonel-lp** [comment]
Actually the values are correct, I was initially confused by the fact that some devices are reported twice, once with the device name and a raw value I'm guessing, and again with the user assigned label and correct value. 

Also barometer value needs to be /100

I've added an inclinometer to my fork of your code, I'm guessing device 13 is that, and it's reporting one of the inclinometer values I think, but I'm only familiar with very basic coding so flying by the seat of my pants.  I don't know how to get the code to pull the correct two values. 

Also in device.py, using the name=property_dict.strings[3] to define the device name for my inclinometer instance (like you've done for other devices) causes the built code to bail with an error. The inclinometer isn't the most important, but would be nice if it worked. 

Really, if the output could exclude the double instances and output to mqtt then youd make many people happy I suspect. 

I'm going to message David simarine tomorrow to see if he'd be happy to provide some info on device id's. Don't know if you have contacted them or not.

**Comment by christopher-strack** [comment]
@colonel-lp I don't think the sensor values are correct yet. For example your starter battery reports 0.023V and the tank level reports 16 (which is 1600% capacity). It looks like all values until the device "Alternator" are correct and afterwards the sensor values look mixed up. I thought it's just a simple offset issue but I can't seem to see any reasonable voltage number for your starter battery for example. That's why I'm asking you to provide the values as they are reported in the app. 

Adding support for the inclinometer and fixing the barometer is no problem of course. I'm happy to take care of that.

**Comment by christopher-strack** [comment]
@colonel-lp I released v0.7.0 with support for the Inclinometer and a fix for the barometer.

I haven't been in touch with folks from Simarine, let me know if they are willing to share implementation details.

**Comment by colonel-lp** [comment]
That's great. Yes I just scanned the output and didn't see the incorrect values. 

I'll capture the output and let you know what the values should be.

**Comment by colonel-lp** [comment]
here is the sensor data, ive added a note at the end of each line, some data just has decimal wrong, some swapped data, some wrong.

[sensors.log](https://github.com/user-attachments/files/18271132/sensors.log)

**Comment by colonel-lp** [comment]
I had a play with pico2signalk last night and also had some mixed up values. I'm assuming this doesn't happen for your setup? I'm going to try deleting and redefining the incorrect sensors to see if it makes any difference.

**Comment by christopher-strack** [comment]
@colonel-lp great I'll have a look at your annotated sensor values and see whether I can spot a pattern for how the sensor values are mapped.

The pico2signalk code worked immediately for me and I'm using it already for quite some time now in my van

**Comment by christopher-strack** [comment]
@colonel-lp I looked at the data but can't make sense of it. For example the annotations mention that the Starter battery voltage sensor reports 26.84V but I cannot find any value that is close to this from the `debug.log`. Could it be that it changed since you generated the `debug.log`? It's important to have the logging and the current values side-by-side so I can spot a pattern on how they are mapped.

It would be most helpful to have a fresh `debug.log` and the current values for each sensor that you have configured by name (no need to look at the unconfigured sensors and please just the bare names and their values, no interpretations on what might be wrong).

**Comment by colonel-lp** [comment]
I'll have a look later, sorry, I forgot a fresh debug.log, although I doubt starter voltage would be much different. I contacted simarine and David said he'd speak to the Devs when they are back on the 6th Jan. I wouldn't hold out for too much back from them though. 

Is there any documentation on decoding the raw data? Means I could look myself too.

**Comment by colonel-lp** [comment]
So. It seems that my old creaking database was the problem, looks like devices were saved in formats that Simarine can read but the pico2signalk code does not understand, initially removing and adding devices caused many more key errors and higher device IDs. Resetting my Pico and restoring a backup put everything back in its correct place.

So the only two values that don't seem to be correct in your code are battery: nominal capacity and capacity remaining. I had to alter the pico2signalk code by dividing by 432 and shifting decimal places to get it correct, but his code gives different values to yours for these. If you still want logs let me know and I'll try to get them later.

**Comment by christopher-strack** [comment]
@colonel-lp glad I'm glad things are working now. It's still a bit unsatisfying that the library can't handle all configurations.

"nominal capacity" as provided by pico2signalk isn't available in this library. I'm only providing the values that are part of the Simarine state message, which is the state of charge and the remaining capacity in ampere hours. But you can easily calculate these values based on the existing values.

In case the values are actually wrong I'm happy to take a look if you provide a new `debug.log` and ideally all configured sensor values (important in case something gets mapped wrongly).

**Comment by colonel-lp** [comment]
yeah, i dont know what to think about the data, considering the state of the Simarine firmware/software and bugs, im not surprised. I'll still see if the devs are willing to share any documentation when David passes on my requests. Just getting all the ids would be a start. Are you on the Facebook group?

from the output of your script:
Battery(device_id=48, name='Ella  ', capacity=-95.36, battery_type=<BatteryType.LIFEPO4: 6>, charge=ChargeSensor(sensor_id=6200, value=0.966), remaining_capacity=CapacitySensor(sensor_id=6201, value=-114.04), current=CurrentSensor(sensor_id=6202, value=-4.97), voltage=VoltageSensor(sensor_id=6203, value=13.035)),
 
capacity=-95.36, should be 560
CapacitySensor(sensor_id=6201, value=-114.04) should be 540.96

assuming im understanding what your values are refering to, and 

charge=ChargeSensor(sensor_id=6200, value=0.966) is correct as 96.6%

**Comment by christopher-strack** [comment]
As I said I need the `debug.log` and all sensor values of the configured devices. Here is a perfect example of such a report https://github.com/christopher-strack/spymarine/issues/20#issuecomment-2564418822.

> yeah, i dont know what to think about the data, considering the state of the Simarine firmware/software and bugs, im not surprised.

I don't think this is a Simarine bug, this library is simply not complete yet. I might need to capture the network communication between the app and the Simarine device to find out more. I didn't do this yet because the pico2signalk approach worked for me but would first want to collect more data for non-working setups.

> Are you on the Facebook group?

No I'm not on that group
